import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Providers } from "@/store/providers";
import { AppChrome } from "@/components/layout/AppChrome/AppChrome";
import { getCategories, getUser } from "@/services/apiServer";
import {
  buildGuestThemeBootstrapScript,
  DEFAULT_THEME_MODE,
  resolveThemeFromCookieHeader,
} from "@/services/themePreference";
import type { Category } from "@/types/category";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const staticLayoutCategories: Category[] = [
  { id: "building-materials", name: "Будівельні матеріали", subcategories: [] },
  { id: "tools", name: "Інструменти", subcategories: [] },
  { id: "plumbing", name: "Сантехніка", subcategories: [] },
  { id: "electro", name: "Електротовари", subcategories: [] },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const [categories, currentUser] = await Promise.all([
    getCategories(),
    getUser(),
  ]);
  const guestTheme =
    resolveThemeFromCookieHeader(cookieStore.toString()) ?? DEFAULT_THEME_MODE;
  const initialTheme = currentUser
    ? currentUser.theme ?? DEFAULT_THEME_MODE
    : guestTheme;
  const resolvedCategories =
    categories.length === 0 ? staticLayoutCategories : categories;

  return (
    <html lang="en" data-theme={initialTheme} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {!currentUser ? (
          <Script id="theme-bootstrap" strategy="beforeInteractive">
            {buildGuestThemeBootstrapScript(initialTheme)}
          </Script>
        ) : null}
        <Providers initialTheme={initialTheme} initialUser={currentUser}>
          <AppChrome
            categories={resolvedCategories}
            initialTheme={initialTheme}
          >
            {children}
          </AppChrome>
        </Providers>
      </body>
    </html>
  );
}
